<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-09LJIS2" failures="3" tests="21" name="Test" time="0.178" errors="0" timestamp="2020-12-23T17:11:43 IST">
  <testcase classname="carLoanTest" name="carFailedTest" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at carLoanTest.carFailedTest(carLoanTest.java:126)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- carFailedTest -->
  <testcase classname="carLoanTest" name="carLoanLogin" time="0.0"/>
  <testcase classname="carLoanTest" name="carLoanLogin" time="0.001"/>
  <testcase classname="carLoanTest" name="carLoanLogin" time="0.002"/>
  <testcase classname="carLoanTest" name="parameterCar" time="0.004"/>
  <testcase classname="carLoanTest" name="carLoanView" time="0.0"/>
  <testcase classname="carLoanTest" name="carLoanSignout" time="0.0"/>
  <testcase classname="personalLoanTest" name="PersonalLoanLogin" time="0.001"/>
  <testcase classname="personalLoanTest" name="PersonalLoanLogin" time="0.0"/>
  <testcase classname="personalLoanTest" name="PersonalLoanLogin" time="0.008"/>
  <testcase classname="personalLoanTest" name="parameterPersonal" time="0.003"/>
  <testcase classname="personalLoanTest" name="personalFailedTest" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at personalLoanTest.personalFailedTest(personalLoanTest.java:127)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- personalFailedTest -->
  <testcase classname="personalLoanTest" name="PersonalLoanView" time="0.0"/>
  <testcase classname="personalLoanTest" name="PersonalLoanSignout" time="0.001"/>
  <testcase classname="homeLoanTest" name="HomeFailedTest" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at homeLoanTest.HomeFailedTest(homeLoanTest.java:124)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- HomeFailedTest -->
  <testcase classname="homeLoanTest" name="HomeLoanLogin" time="0.0"/>
  <testcase classname="homeLoanTest" name="HomeLoanLogin" time="0.0"/>
  <testcase classname="homeLoanTest" name="HomeLoanLogin" time="0.0"/>
  <testcase classname="homeLoanTest" name="parameterHome" time="0.001"/>
  <testcase classname="homeLoanTest" name="HomeLoanView" time="0.0"/>
  <testcase classname="homeLoanTest" name="HomeLoanSignout" time="0.001"/>
</testsuite> <!-- Test -->
